# -*- coding: utf-8 -*-
"""text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZu4sUadWVe3Zl8qD5LcIh9ZQxfaHlRd
"""

import streamlit as st
import mysql.connector
st.title("EMPLOYEE MANAGEMENT SYSTEM")
choice=st.sidebar.selectbox("My Menu",("Home","User","Admin"))
if(choice=="Home"):
    st.image("https://img.freepik.com/free-vector/business-people-showing-document-client_1262-19209.jpg")
    st.write("This is a web application developed by me")
elif(choice=="User"):
    btn2=st.button("Temporary")
    if 'login' not in st.session_state:
        st.session_state['login']=False
    login=False
    eid=st.text_input("Enter Employee ID")
    epwd=st.text_input("Enter password")
    btn=st.button("Login")
    if btn:
        mydb=mysql.connector.connect(host="localhost",user="root",password="Raginee123@",database="ems")
        c=mydb.cursor()
        c.execute("select * from employees")
        for r in c:
                  if (r[0]==eid and r[4]==epwd):
                      st.session_state['login']=True

        if(not st.session_state['login']):
            st.write("Incorrect ID or Password")
    if(st.session_state['login']):
        st.write("Login Successful")
    st.write(st.session_state['login'])




elif(choice=="Admin"):
    st.video("https://www.youtube.com/watch?v=zkPQSg1a1zA")

!pip install streamlit
import streamlit as st
import mysql.connector
st.title("EMPLOYEE MANAGEMENT SYSTEM")
choice=st.sidebar.selectbox("My Menu",("Home","User","Admin"))
if(choice=="Home"):
    st.image("https://img.freepik.com/free-vector/business-people-showing-document-client_1262-19209.jpg")
    st.write("This is a web application developed by me")
elif(choice=="User"):
    btn2=st.button("Temporary")
    if 'login' not in st.session_state:
        st.session_state['login']=False
    login=False
    eid=st.text_

!pip install streamlit
!pip install mysqlclient # Install the required package for mysql.connector
import streamlit as st
import mysql.connector # Now this import should work
st.title("EMPLOYEE MANAGEMENT SYSTEM")
choice=st.sidebar.selectbox("My Menu",("Home","User","Admin"))
if(choice=="Home"):
    st.image("https://img.freepik.com/free-vector/business-people-showing-document-client_1262-19209.jpg")
    st.write("This is a web application developed by me")
elif(choice=="User"):
    btn2=st.button("Temporary")
    if 'login' not in st.session_state:
        st.session_state['login']=False
    login=False
    eid=st.text_input("Enter Employee ID")
    epwd=st.text_input("Enter password")
    btn=st.button("Login")
    if btn:
        mydb=mysql.connector.connect(host="localhost",user="root",password="Raginee123@",database="ems")
        c=mydb.cursor()
        c.execute("select * from employees")
        for r in c:
                  if (r[0]==eid and r[4]==epwd):
                      st.session_state['login']=True

        if(not st.session_state['login']):
            st.write("Incorrect ID or Password")
    if(st.session_state['login']):
        st.write("Login Successful")
    st.write(st.session_state['login'])

elif(choice=="Admin"):
    st.video("https://www.youtube.com/watch?v=zkPQSg1a1zA")

!pip install mysql-connector-python # Install mysql-connector-python
import streamlit as st
import mysql.connector # Now this import should work
st.title("EMPLOYEE MANAGEMENT SYSTEM")
choice=st.sidebar.selectbox("My Menu",("Home","User","Admin"))
if(choice=="Home"):
    st.image("https://img.freepik.com/free-vector/business-people-showing-document-client_1262-19209.jpg")
    st.write("This is a web application developed by me")
elif(choice=="User"):
    btn2=st.button("Temporary")
    if 'login' not in st.session_state:
        st.session_state['login']=False
    login=False
    eid=st.text_input("Enter Employee ID")
    epwd=st.text_input("Enter password")
    btn=st.button("Login")
    if btn:
        mydb=mysql.connector.connect(host="localhost",user="root",password="Raginee123@",database="ems")
        c=mydb.cursor()
        c.execute("select * from employees")
        for r in c:
                  if (r[0]==eid and r[4]==epwd):
                      st.session_state['login']=True

        if(not st.session_state['login']):
            st.write("Incorrect ID or Password")
    if(st.session_state['login']):
        st.write("Login Successful")
!pip install mysql-connector-python # Install mysql-connector-python
import streamlit as st
import mysql.connector # Now this import should work
st.title("EMPLOYEE MANAGEMENT SYSTEM")
choice=st.sidebar.selectbox("My Menu",("Home","User","Admin"))
if(choice=="Home"):
    st.image("https://img.freepik.com/free-vector/business-people-showing-document-client_1262-19209.jpg")
    st.write("This is a web application developed by me")
elif(choice=="User"):
    btn2=st.button("Temporary")
    if 'login' not in st.session_state:
        st.session_state['login']=False
    login=False
    eid=st.text_input("Enter Employee ID")
    epwd=st.text_input("Enter password")
    btn=st.button("Login")
    if btn:
        mydb=mysql.connector.connect(host="localhost",user="root",password="Raginee123@",database="ems")
        c=mydb.cursor()
        c.execute("select * from employees")
        for r in c:
                  if (r[0]==eid and r[4]==epwd):
                      st.session_state['login']=True

        if(not st.session_state['login']):
            st.write("Incorrect ID or Password")
    if(st.session_state['login']):
        st.write("Login Successful")
    st.write(st.session_state['login'])

elif(choice=="Admin"):
    pass